[package]
name = "angular"
version = "0.1.1"
authors = ["Oliver Mader <b52@reaktor42.de>"]
description = "Angular types and common helper methods."
documentation = "https://b52.github.io/angular-rust"
homepage = "https://github.com/b52/angular-rust"
repository = "https://github.com/b52/angular-rust.git"
readme = "README.md"
keywords = ["angle", "geometry", "orientation", "degree", "radian"]
license = "MIT"

[dependencies]
num = "^0.1.27"

[dev-dependencies]
hamcrest = "^0.1.0"
quickcheck = "^0.2.21"
